version: '3'
services:
  web:
    depends_on:
      - dev
    build:
      dockerfile: docker/web/Dockerfile
      context: .
    volumes:
      - ./dist:/usr/share/nginx/html
    ports:
      - "8080:80"
    networks:
      - default
  dev:
    build:
      dockerfile: docker/dev/Dockerfile
      context: .
    command: sh -c 'chmod +x ./docker/*.sh && ./docker/ssh-keys.sh && npm i && npm run build && npm run dev'
    volumes:
      - ./:/app
      - ~/.ssh:/root/.ssh-keys:ro
    restart: always
    networks:
      - default
    ports:
      - "3000:3000"

networks:
  default:
    internal: true
  studiolabs-dev:
    external:
